### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by iamguyfawkes** [AlexanderGrom/php-qevix#1]
Здравствуйте, отличная либа.
Добавьте возможность установки через composer.
https://getcomposer.org

**Comment by AlexanderGrom** [comment]
Добавил.
`require: "qevix/qevix": "dev-master"`
или начиная с версии 0.2.2:
`require: "qevix/qevix": "0.2.2"`

**Comment by iamguyfawkes** [comment]
спасибо
