### ISSUE TITLE
Параметры неразрешенных тегов - нужно ли исключение?

### ISSUE THREAD

**Issue by aVadim483** [AlexanderGrom/php-qevix#12]
Сейчас, если сам тег не задан, а для него задаются какие-то параметры, то выбрасывается исключение, да еще с русским текстом. 

На мой взгляд, это не очень логично - текст ведь может быть обработан, просто нет возможности задать параметры для неразрешенных тегов. И действуем по принципу "запрещено все, что явно не разрешено".

Предлагаю: исключения не выбрасывать, а писать, скажем, в массив warnings и дать возможность его получать. В warnings писать код "предупреждения" и доп. параметры. Класс Qevix все равно не используется самостоятельно, у него всегда есть какая-то обертка, и решение о том, что делать, лучше делать на более высоком уровне.

Очевидный плюс такого подхода: я могу описать полный набор всех параметров и разрешений для всех возможных тегов, и уже в зависимости от ситуации задавать тот или иной набор тегов, напр., для поста - один набор, для коммента - другой, хотя наборы параметров тегов в обоих случаях одинаковые.

**Comment by AlexanderGrom** [comment]
Где-то Exception нужен, где-то не очень. Я подумаю над этим. Сейчас можно просто вызывать методы конфигурации в блоке try/catch. Если Exception не нужен, просто игнорируйте его.
