### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by BIT-you** [AlexanderGrom/php-qevix#13]
Возможно, это не связано c qevix, но на всякий случай спрошу: на сайте в текстовом редакторе не работает Enter, если пользователь c FireFox. Все перерыл, а причину найти не могу. Что это может быть? Движек AltoCMS.
Заранее спасибо.

**Comment by AlexanderGrom** [comment]
По описанию проблема в текстовом редакторе. Возможно в AltoCMS устаревшая версия.

**Comment by BIT-you** [comment]
Спасибо
