### ISSUE TITLE
Атрибуты без значений. <div itemscope itemtype="http://schema.org/ImageObject">

### ISSUE THREAD

**Issue by anp135** [AlexanderGrom/php-qevix#14]
Не могу заставить qevix пропустить 
`<div itemscope itemtype="http://schema.org/ImageObject">`
Так или иначе происходит удаление атрибута itemscope, что в итоге ломает микроразметку -(.

Просидел с xdebug порядком, но так и не смог победить-разобраться почему при itemscope="" - работает, а просто itemscope - нет -(.

**Comment by AlexanderGrom** [comment]
Да. Парсер должен был преобразовать атрибут в XHTML валидный стиль `itemscope="itemscope"`, но там закралась ошибка.

Сейчас я добавил поддержку булевых атрибутов. Делается это по средствам шаблона `#bool`.

Например:
`$qevix->cfgAllowTagParams('div', ['itemscope' => '#bool', 'itemtype' => ['#link' => ['schema.org']]]);`

Для Вашей сроки при `$qevix->cfgSetXHTMLMode(false);` выход будет в стиле HTML5:
`<div itemscope itemtype="http://schema.org/ImageObject"></div>`

Если включен режим XHTML, то:
`<div itemscope="itemscope" itemtype="http://schema.org/ImageObject"></div>`

Надеюсь я Вам помог.

**Comment by anp135** [comment]
благодарю! 

надеюсь смогу протянуть `$qevix->cfgSetXHTMLMode(false);`  в настройках AltoCMS.
