### ISSUE TITLE
Тег <img> XHTML

### ISSUE THREAD

**Issue by programmator** [AlexanderGrom/php-qevix#2]
Если передать фильтру тег `<img>` стандарте XHTML:

``` html
<img src="..." alt="..." title="..." />
```

То вернёт его без первого символа `<`:

``` html
img src="..." alt="..." title="..." />
```

Включением и отключением `cfgSetXHTMLMode` ситуация не меняется.

**Comment by AlexanderGrom** [comment]
Поправил. Спасибо за замечание.
