### ISSUE TITLE
Предложение по обработке cfgSetTagBuildCallback()

### ISSUE THREAD

**Issue by aVadim483** [AlexanderGrom/php-qevix#5]
При вызове коллбэк-фунции, заданной в `cfgSetTagBuildCallback` предлагаю в третьем аргументе (контент) для непарных тегов (типа `img`) передавать `null`. Для парных тегов, если контента нет, передавать пустую строку. Тогда в собственном обработчике гораздо проще будет определять, должен быть закрывающий тег или нет: если `null`, то имеем дело с непарным тегом закрывающий тег не нужен, в противном случае - закрывающий тег нужен.

В Jevix, кстати, именно такая логика и была

**Comment by AlexanderGrom** [comment]
Только в Jexiv из LS.

Тут у меня вопрос: Мы вешаем на непарный тег callback-функцию, например, она называется `tagImgBuilder(...)`. Соответственно в функции должен обрабатываться непарный тег `img`. Вешать несколько разных тегов на одну функцию, наверно не очень.  Все непарные теги указаны в `cfgSetTagShort`, их там должно быть по пальцам пересчитать, а одновременно парным и непарный он быть не может. 

Не могу сейчас придумать более специфичную задачу, что бы оправдать эту возможность.
