### ISSUE TITLE
Проблемы с использованием jevix

### ISSUE THREAD

**Issue by ogimihail** [AlexanderGrom/php-qevix#6]
Здравствуйте, я решил использовать ваш класс для фильтрации пользовательского ввода, настроил все, как указано в инструкции, тестовый пример фильтруется правильно (когда он пишется непосредственно в php-файле и храниться в переменной), но когда я беру $_POST["news_body"];, то обработка происходит некорректно, например лишние восклицательные знаки убираются, а вот такой код '<script> 11111 </script>' (пропускает неразрешенные теги), подскажите, пожалуйста, в каком направлении двигаться, чтобы выявить ошибку.

**Comment by AlexanderGrom** [comment]
Вы пишите в заголовке Jevix и упоминаете удаление лишних восклицательных знаков. Такой функционал действительно реализован в Jevix, но отсутствует в Qevix. 

Вы хотели указать код, который пропускает теги. К сожалению я его не вижу.

Уточните, что вы используете Jevix или Qevix?
Покажите текст в котором пропускаются неразрешенные теги.

**Comment by ogimihail** [comment]
Я сначала, пропустил через Qevix, не получилось отфильтровать, потом решил пропустить через Jevix, получился тот же результат (случайно вышло, что я обратил внимание на !!!, хотя помимо них фильтрация работала аналогично для тех символов, которые я наблюдал). Пока ждал ответ, я еще покопался, и нашел ошибку, из формы из-за некоторого упущения приходил вместо "<" его спецсимвол html. Поэтому тут проблема ясна, но возник вопрос, если Jevix и Qevix не считают этот спецсимвол значком открытия тега, то они его пропустят, а после вывода отфильтрованного html в браузер, этот спецсимвол там преобразуется обратно в < (в итоге может получиться что-то типа <скрипт>...код... </скрипт>), я понимаю, что этот "тег" и его содержимое выведутся просто как текст, а не, к примеру, как скрипт, но все же не будет ли какой-либо уязвимости в том, что текст вредноносного кода отправится пользователю в браузер?

**Comment by AlexanderGrom** [comment]
Вход: `&lt;script>alert(1);</script>`
Результат: `&#60;script&#62;alert(1)`

Это нормальное поведение, парсер рассматривает `&lt;script>alert(1);` просто как текст, а закрывающий тег отбрасывается.

**Comment by ogimihail** [comment]
Понятно, благодарю.
