### ISSUE TITLE
Нет обработки доменов в атрибутах

### ISSUE THREAD

**Issue by aVadim483** [AlexanderGrom/php-qevix#8]
В Jevix есть возможность задать список допустимых доменов через параметр `#domain` (напр., при конфигурировании тега `iframe`). Не знаю, было ли это в нем изначально или это модифицированный вариант, но в LS это было.

В Qevix этого нет. Конечно, можно задать их с помощью регулярного выражения, но задать в массиве простой перечень доменов гораздо проще, особенно для новичков.

**Comment by AlexanderGrom** [comment]
С наступающим! :)

**Comment by aVadim483** [comment]
Спасибо! С наступившим!

**Comment by AlexanderGrom** [comment]
Так. Да, это есть только в версии LS. Мне кажется, в место того, что бы усложнять парсер, этот функционал лучше вынести в callback и сделать нормальную проверку. Особенно если это касается iframe и других тегов загрузки внешний ресурсов, которые в 99.9% случаях должны быть отключены. 

Если мы вводим новый тег, например, video, который будет преобразовываться в iframe с ссылкой на ролик (youtube, vimeo). Для него нам всеровно нужен callback с полной проверкой адреса, а не только домена. А то получится так, что мы можем внедрить в страницу не видео, а все что угодно с этого домена.

Допустим проверка на просто страницу с видео на YouTube могла бы выглядеть как-то так:

```
function tag_video_build($tag, $params, $content)
{   
    if(preg_match('#^(?:http|https)://www\.youtube\.com/watch\?v=(?P<name>[0-9a-z_\-]+)(?:&(.*?))?$#isu', $params['src'], $match)) {
        $src = 'http://www.youtube.com/embed/'.$match['name'];
    } else {
        return '';
    }   
    return '<iframe width="650" height="360" src="'.$src.'" frameborder="0" allowfullscreen></iframe>';
}
```

**Comment by aVadim483** [comment]
Я ж говорю, что проверку сделать имеющимися средствами можно и сейчас. Вопрос в удобстве конфигурирования. Через iframe не только видео вставляется, это могут быть и какие-то презентации, и товары онлайн-магазинов, какие-то карты, да много чего. И если сайт клепает программер, то он, конечно, найдет варианты, как фильтровать и преобразовывать теги.

Но если при создании сайта использовать просто встроенные возможности CMS, то задача для человека неискушенного становится почти нерешаемой (но "почти", потому что есть регулярка, как писал выше).

Хотя для меня фича, конечно, некритична. Тем более, что планирую на уровне конфигурирования CMS использовать несколько иной подход для настройки парсера.

Но в целом парсер нравится и в следующей версии в Alto CMS он станет основным, заменив собой Jevix.

**Comment by AlexanderGrom** [comment]
Да, обычные пользователи требуют внимания. С другой стороны, ссылки на онлайн товары, презентации, игры, видео, карты требуют более глубокой проверки адреса, чем просто домен. Иначе можно будет вставить любою другую страницу с этого домена. Если записи добавляет только администратор, то такие проверки может и не нужны, но если пользователи, то это довольно критично. Я подумаю над более полной и простой проверкой.

**Comment by AlexanderGrom** [comment]
Я подумал и не нашел лучшего решения, как указывать только домены. Можно было бы сделать маски и правила (типа glob), но опять же это только для опытных пользователей.

Вообщем, кому надо, тот может указать список доменов у шаблона `#link`:
`$qevix->cfgAllowTagParams('video', array('src' => array('#link' => ['youtube.com', 'video.com']));`

Сразу стоит сказать отличия от версии в LS.
1. Тут `#link`, а не `#domain`. Так более грамотно и просто;
2. В LS при указании `#domain` не учитывается конфиг `cfgSetLinkProtocolAllow`, т.е. если мы запрещаем протокол ftp, то в параметрах с `#domain` ссылки с ftp проходят;
3. В LS домену соответствовали и его поддомены, т.е если мы задаем example.com, то там проходят и baсkdoor.example.com и это уже через чур.

Загрузил, смотрите, пробуйте.

**Comment by aVadim483** [comment]
Спасибо

Согласен с тем, что только домены и поддоменов по умолчанию быть не должно, если нужны поддомены, то требуется явно их указать. Хотя в при таких условиях параметр `#domain` мне кажется семантически более верным. Но это не принципиально

**Comment by aVadim483** [comment]
Небольшие правки: https://github.com/AlexanderGrom/php-qevix/pull/9
